version: '3.8'

services:
  baleen:
    image: sfs0cr.azurecr.io/baleen-server:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=azure
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SERVER_PORT=8080
    volumes:
      - baleen-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  baleen-logs: